
CREATE USER sparkify WITH  PASSWORD 'sparkify' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION;
CREATE USER awsuser WITH PASSWORD 'Passw0rd' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION;
CREATE DATABASE dev OWNER awsuser;
CREATE DATABASE dest OWNER awsuser;
GRANT sparkify TO awsuser;

