version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      # DAGs example loaded = none
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_PATH=/usr/local/airflow/dags
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./.aws.airflow.credentials:/usr/local/airflow/.aws/credentials
      # - ./plugins:/usr/local/airflow/plugins
      - ./settings/local/:/usr/local/airflow/settings
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3